<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Risk.Domain\Risk.Domain.csproj" />
    <ProjectReference Include="..\Risk.Engine\Risk.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Risk.AI.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
